import React, { useState, useMemo } from 'react';
import { downloadBlob } from '../lib/downloadHelper';
import {
  FileText, Check, Copy, Download, Search, AlertTriangle, Globe, Share2, Code,
  List, BarChart2, Settings, Layers, Eye, RefreshCw, FileCode, Trash2, Plus,
  HelpCircle, CheckCircle2, XCircle, Info, ExternalLink, FileSpreadsheet, BookOpen,
  Sparkles, Filter, ArrowRight, Tag, ChevronDown, ChevronUp, Zap, Award, Layers as Hierarchy
} from 'lucide-react';

// Helper function to copy text
const copyToClipboard = async (text: string, setCopied: (v: boolean) => void) => {
  try {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  } catch (err) {
    console.error('Failed to copy', err);
  }
};

// Helper to download file
const downloadFile = (filename: string, content: string, type: string = 'text/plain') => {
  const blob = new Blob([content], { type });
  downloadBlob(blob, filename);
};

// ============================================================================
// 1. Robots.txt Generator & Validator
// ============================================================================
export const RobotsTxtGenerator: React.FC = () => {
  const [sitemapUrl, setSitemapUrl] = useState('https://example.com/sitemap.xml');
  const [crawlDelay, setCrawlDelay] = useState('');
  const [rules, setRules] = useState([
    { userAgent: '*', type: 'disallow' as 'allow' | 'disallow', path: '/admin/' },
    { userAgent: '*', type: 'disallow' as 'allow' | 'disallow', path: '/private/' },
    { userAgent: 'Googlebot', type: 'allow' as 'allow' | 'disallow', path: '/' },
    { userAgent: 'GPTBot', type: 'disallow' as 'allow' | 'disallow', path: '/' },
  ]);
  const [copied, setCopied] = useState(false);
  const [testUrl, setTestUrl] = useState('/admin/login');
  const [testBot, setTestBot] = useState('*');

  const addRule = () => {
    setRules([...rules, { userAgent: '*', type: 'disallow', path: '' }]);
  };

  const removeRule = (index: number) => {
    setRules(rules.filter((_, i) => i !== index));
  };

  const updateRule = (index: number, field: string, value: string) => {
    const updated = [...rules];
    updated[index] = { ...updated[index], [field]: value };
    setRules(updated);
  };

  const applyPreset = (preset: 'wordpress' | 'ecommerce' | 'ai-block') => {
    if (preset === 'wordpress') {
      setRules([
        { userAgent: '*', type: 'disallow', path: '/wp-admin/' },
        { userAgent: '*', type: 'allow', path: '/wp-admin/admin-ajax.php' },
        { userAgent: '*', type: 'disallow', path: '/readme.html' },
      ]);
    } else if (preset === 'ecommerce') {
      setRules([
        { userAgent: '*', type: 'disallow', path: '/cart/' },
        { userAgent: '*', type: 'disallow', path: '/checkout/' },
        { userAgent: '*', type: 'disallow', path: '/account/' },
        { userAgent: '*', type: 'disallow', path: '/*?*sort=' },
      ]);
    } else if (preset === 'ai-block') {
      setRules([
        { userAgent: 'GPTBot', type: 'disallow', path: '/' },
        { userAgent: 'ChatGPT-User', type: 'disallow', path: '/' },
        { userAgent: 'CCBot', type: 'disallow', path: '/' },
        { userAgent: 'AnthropicAI', type: 'disallow', path: '/' },
        { userAgent: 'ClaudeBot', type: 'disallow', path: '/' },
      ]);
    }
  };

  const robotsTxtContent = useMemo(() => {
    const grouped: Record<string, typeof rules> = {};
    rules.forEach((r) => {
      const agent = r.userAgent.trim() || '*';
      if (!grouped[agent]) grouped[agent] = [];
      grouped[agent].push(r);
    });

    let output = '# Generated by WebTools SEO Suite\n\n';
    Object.entries(grouped).forEach(([agent, agentRules]) => {
      output += `User-agent: ${agent}\n`;
      agentRules.forEach((rule) => {
        if (rule.path) {
          const capitalized = rule.type === 'disallow' ? 'Disallow' : 'Allow';
          output += `${capitalized}: ${rule.path}\n`;
        }
      });
      if (crawlDelay) {
        output += `Crawl-delay: ${crawlDelay}\n`;
      }
      output += '\n';
    });

    if (sitemapUrl) {
      output += `Sitemap: ${sitemapUrl.trim()}\n`;
    }

    return output.trim();
  }, [rules, crawlDelay, sitemapUrl]);

  // Test URL resolution
  const testResult = useMemo(() => {
    if (!testUrl) return null;
    // Check specific agent first, then wildcard *
    const matchingRules = rules.filter(
      (r) => r.userAgent === testBot || r.userAgent === '*'
    );

    let isDisallowed = false;
    let matchedRule = null;

    for (const r of matchingRules) {
      if (!r.path) continue;
      // Simple prefix / wildcard check
      const pattern = r.path.replace(/\*/g, '.*');
      const regex = new RegExp('^' + pattern);
      if (regex.test(testUrl) || testUrl.startsWith(r.path)) {
        if (r.type === 'disallow') {
          isDisallowed = true;
          matchedRule = r;
        } else {
          isDisallowed = false;
          matchedRule = r;
        }
      }
    }

    return {
      allowed: !isDisallowed,
      rule: matchedRule,
    };
  }, [testUrl, testBot, rules]);

  return (
    <div className="space-y-6">
      {/* Header & Preset Buttons */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-secondary/40 p-4 rounded-xl border border-border">
        <div>
          <h3 className="text-sm font-semibold text-foreground">Quick Presets</h3>
          <p className="text-xs text-muted-foreground">Apply optimized rule templates for popular platforms</p>
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={() => applyPreset('wordpress')}
            className="px-3 py-1.5 text-xs font-medium rounded-lg bg-background border border-border text-foreground hover:bg-secondary/60 transition"
          >
            WordPress
          </button>
          <button
            onClick={() => applyPreset('ecommerce')}
            className="px-3 py-1.5 text-xs font-medium rounded-lg bg-background border border-border text-foreground hover:bg-secondary/60 transition"
          >
            E-Commerce
          </button>
          <button
            onClick={() => applyPreset('ai-block')}
            className="px-3 py-1.5 text-xs font-medium rounded-lg bg-background border border-border text-foreground hover:bg-secondary/60 transition"
          >
            Block AI Scrapers
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Configuration Form */}
        <div className="lg:col-span-7 space-y-5">
          <div className="bg-card border border-border rounded-xl p-5 space-y-4 shadow-xs">
            <h4 className="font-semibold text-foreground text-sm flex items-center gap-2">
              <Settings className="w-4 h-4 text-indigo-600" /> General Directives
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              <div className="md:col-span-2">
                <label className="block text-xs font-medium text-foreground mb-1">Sitemap URL</label>
                <input
                  type="url"
                  value={sitemapUrl}
                  onChange={(e) => setSitemapUrl(e.target.value)}
                  placeholder="https://example.com/sitemap.xml"
                  className="w-full px-3 py-2 text-xs border border-border rounded-lg focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
                />
              </div>
              <div>
                <label className="block text-xs font-medium text-foreground mb-1">Crawl Delay (s)</label>
                <input
                  type="number"
                  value={crawlDelay}
                  onChange={(e) => setCrawlDelay(e.target.value)}
                  placeholder="e.g., 5"
                  className="w-full px-3 py-2 text-xs border border-border rounded-lg focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
                />
              </div>
            </div>
          </div>

          {/* Rules Builder */}
          <div className="bg-card border border-border rounded-xl p-5 space-y-4 shadow-xs">
            <div className="flex items-center justify-between">
              <h4 className="font-semibold text-foreground text-sm flex items-center gap-2">
                <List className="w-4 h-4 text-indigo-600" /> Crawl Directives ({rules.length})
              </h4>
              <button
                onClick={addRule}
                className="px-3 py-1.5 text-xs font-medium bg-indigo-50 text-indigo-600 hover:bg-indigo-100 rounded-lg flex items-center gap-1 transition"
              >
                <Plus className="w-3.5 h-3.5" /> Add Rule
              </button>
            </div>

            <div className="space-y-3 max-h-[380px] overflow-y-auto pr-1">
              {rules.map((rule, idx) => (
                <div key={idx} className="flex flex-wrap md:flex-nowrap items-center gap-2 p-3 bg-secondary/40 border border-border rounded-lg">
                  <select
                    value={rule.userAgent}
                    onChange={(e) => updateRule(idx, 'userAgent', e.target.value)}
                    className="text-xs px-2.5 py-1.5 bg-background border border-border rounded-lg font-medium text-foreground focus:outline-hidden"
                  >
                    <option value="*">* (All Bots)</option>
                    <option value="Googlebot">Googlebot</option>
                    <option value="Bingbot">Bingbot</option>
                    <option value="GPTBot">GPTBot (OpenAI)</option>
                    <option value="ClaudeBot">ClaudeBot</option>
                    <option value="CCBot">CCBot</option>
                    <option value="Baiduspider">Baiduspider</option>
                    <option value="Yandex">Yandex</option>
                  </select>

                  <select
                    value={rule.type}
                    onChange={(e) => updateRule(idx, 'type', e.target.value)}
                    className={`text-xs px-2 py-1.5 font-semibold rounded-lg border focus:outline-hidden ${
                      rule.type === 'disallow'
                        ? 'bg-rose-50 text-rose-700 border-rose-200'
                        : 'bg-emerald-50 text-emerald-700 border-emerald-200'
                    }`}
                  >
                    <option value="disallow">Disallow</option>
                    <option value="allow">Allow</option>
                  </select>

                  <input
                    type="text"
                    value={rule.path}
                    onChange={(e) => updateRule(idx, 'path', e.target.value)}
                    placeholder="/path/to/block/"
                    className="flex-1 text-xs px-3 py-1.5 bg-background border border-border rounded-lg focus:outline-hidden font-mono text-foreground"
                  />

                  <button
                    onClick={() => removeRule(idx)}
                    className="p-1.5 text-muted-foreground hover:text-rose-600 rounded-lg hover:bg-rose-50 transition"
                    title="Remove rule"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* Rule Testing Simulator */}
          <div className="bg-indigo-50/60 border border-indigo-100 rounded-xl p-4 space-y-3">
            <h5 className="text-xs font-bold text-indigo-950 uppercase tracking-wider flex items-center gap-1.5">
              <Zap className="w-3.5 h-3.5 text-indigo-600" /> Live URL Rule Tester
            </h5>
            <div className="grid grid-cols-1 sm:grid-cols-12 gap-2">
              <select
                value={testBot}
                onChange={(e) => setTestBot(e.target.value)}
                className="sm:col-span-4 text-xs px-2.5 py-1.5 bg-white border border-indigo-200 rounded-lg text-foreground"
              >
                <option value="*">* (All Bots)</option>
                <option value="Googlebot">Googlebot</option>
                <option value="GPTBot">GPTBot</option>
              </select>
              <input
                type="text"
                value={testUrl}
                onChange={(e) => setTestUrl(e.target.value)}
                placeholder="/admin/login"
                className="sm:col-span-8 text-xs px-3 py-1.5 bg-white border border-indigo-200 rounded-lg font-mono"
              />
            </div>
            {testResult && (
              <div
                className={`p-2.5 rounded-lg text-xs font-medium flex items-center justify-between ${
                  testResult.allowed
                    ? 'bg-emerald-100/80 text-emerald-900 border border-emerald-200'
                    : 'bg-rose-100/80 text-rose-900 border border-rose-200'
                }`}
              >
                <span className="flex items-center gap-1.5">
                  {testResult.allowed ? (
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                  ) : (
                    <XCircle className="w-4 h-4 text-rose-600" />
                  )}
                  {testResult.allowed
                    ? `ALLOWED: Crawlers can index "${testUrl}"`
                    : `BLOCKED: Crawlers are prohibited from accessing "${testUrl}"`}
                </span>
                {testResult.rule && (
                  <span className="font-mono text-[10px] bg-white/70 px-2 py-0.5 rounded">
                    Rule: {testResult.rule.type} {testResult.rule.path}
                  </span>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Right: Code Output */}
        <div className="lg:col-span-5 flex flex-col space-y-3">
          <div className="flex items-center justify-between">
            <h4 className="font-semibold text-foreground text-sm flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-600" /> Generated robots.txt
            </h4>
            <div className="flex items-center gap-2">
              <button
                onClick={() => copyToClipboard(robotsTxtContent, setCopied)}
                className="px-2.5 py-1 text-xs font-medium rounded-lg bg-indigo-600 text-white hover:bg-indigo-700 flex items-center gap-1 transition shadow-xs"
              >
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied' : 'Copy'}
              </button>
              <button
                onClick={() => downloadFile('robots.txt', robotsTxtContent)}
                className="px-2.5 py-1 text-xs font-medium rounded-lg bg-secondary/60 text-foreground hover:bg-secondary flex items-center gap-1 transition"
              >
                <Download className="w-3.5 h-3.5" /> Download
              </button>
            </div>
          </div>

          <pre className="flex-1 bg-slate-900 text-slate-100 p-4 rounded-xl text-xs font-mono overflow-x-auto border border-slate-800 min-h-[380px] leading-relaxed">
            {robotsTxtContent}
          </pre>
        </div>
      </div>
    </div>
  );
};

// ============================================================================
// 2. Sitemap XML Generator & Visualizer
// ============================================================================
export const SitemapXmlGenerator: React.FC = () => {
  const [baseUrl, setBaseUrl] = useState('https://example.com');
  const [urls, setUrls] = useState([
    { path: '/', lastmod: '2026-08-01', changefreq: 'daily', priority: '1.0' },
    { path: '/about', lastmod: '2026-07-20', changefreq: 'monthly', priority: '0.8' },
    { path: '/services', lastmod: '2026-07-25', changefreq: 'weekly', priority: '0.9' },
    { path: '/blog', lastmod: '2026-08-04', changefreq: 'daily', priority: '0.8' },
    { path: '/contact', lastmod: '2026-06-15', changefreq: 'yearly', priority: '0.5' },
  ]);
  const [bulkInput, setBulkInput] = useState('');
  const [showBulkModal, setShowBulkModal] = useState(false);
  const [copied, setCopied] = useState(false);

  const addUrl = () => {
    setUrls([
      ...urls,
      {
        path: '/new-page',
        lastmod: new Date().toISOString().split('T')[0],
        changefreq: 'weekly',
        priority: '0.7',
      },
    ]);
  };

  const removeUrl = (index: number) => {
    setUrls(urls.filter((_, i) => i !== index));
  };

  const updateUrl = (index: number, field: string, value: string) => {
    const updated = [...urls];
    updated[index] = { ...updated[index], [field]: value };
    setUrls(updated);
  };

  const handleBulkImport = () => {
    const lines = bulkInput.split('\n').map((l) => l.trim()).filter(Boolean);
    const today = new Date().toISOString().split('T')[0];
    const newItems = lines.map((line) => {
      let cleanPath = line;
      if (line.startsWith('http://') || line.startsWith('https://')) {
        try {
          const parsed = new URL(line);
          cleanPath = parsed.pathname + parsed.search;
        } catch {}
      }
      if (!cleanPath.startsWith('/')) cleanPath = '/' + cleanPath;
      return { path: cleanPath, lastmod: today, changefreq: 'weekly', priority: '0.8' };
    });
    setUrls([...urls, ...newItems]);
    setBulkInput('');
    setShowBulkModal(false);
  };

  const xmlContent = useMemo(() => {
    const cleanBase = baseUrl.replace(/\/$/, '');
    let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
    xml += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

    urls.forEach((item) => {
      const fullUrl = `${cleanBase}${item.path.startsWith('/') ? '' : '/'}${item.path}`;
      xml += `  <url>\n`;
      xml += `    <loc>${fullUrl}</loc>\n`;
      if (item.lastmod) xml += `    <lastmod>${item.lastmod}</lastmod>\n`;
      if (item.changefreq) xml += `    <changefreq>${item.changefreq}</changefreq>\n`;
      if (item.priority) xml += `    <priority>${item.priority}</priority>\n`;
      xml += `  </url>\n`;
    });

    xml += `</urlset>`;
    return xml;
  }, [baseUrl, urls]);

  return (
    <div className="space-y-6">
      {/* Top Controls */}
      <div className="bg-card border border-border rounded-xl p-4 flex flex-wrap items-center justify-between gap-4 shadow-xs">
        <div className="flex-1 min-w-[240px]">
          <label className="block text-xs font-semibold text-foreground mb-1">Domain / Base URL</label>
          <input
            type="url"
            value={baseUrl}
            onChange={(e) => setBaseUrl(e.target.value)}
            placeholder="https://yourdomain.com"
            className="w-full px-3 py-2 text-xs border border-border rounded-lg focus:ring-2 focus:ring-indigo-500 focus:outline-hidden font-mono"
          />
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowBulkModal(true)}
            className="px-3 py-2 text-xs font-medium bg-secondary/60 hover:bg-secondary text-foreground rounded-lg transition flex items-center gap-1.5"
          >
            <FileSpreadsheet className="w-4 h-4 text-indigo-600" /> Bulk Paste URLs
          </button>
          <button
            onClick={addUrl}
            className="px-3 py-2 text-xs font-medium bg-indigo-600 text-white hover:bg-indigo-700 rounded-lg transition flex items-center gap-1.5"
          >
            <Plus className="w-4 h-4" /> Add Single Page
          </button>
        </div>
      </div>

      {/* URL Table Editor */}
      <div className="bg-card border border-border rounded-xl overflow-hidden shadow-xs">
        <div className="p-4 bg-secondary/40 border-b border-border flex items-center justify-between">
          <h4 className="text-xs font-bold text-foreground uppercase tracking-wider">
            Sitemap URL Entries ({urls.length})
          </h4>
          <span className="text-xs text-muted-foreground">Max recommended per file: 50,000 URLs</span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-secondary/60 text-muted-foreground font-semibold border-b border-border">
              <tr>
                <th className="p-3">Path / Relative URL</th>
                <th className="p-3 w-36">Last Modified</th>
                <th className="p-3 w-32">Frequency</th>
                <th className="p-3 w-28">Priority</th>
                <th className="p-3 w-12 text-center">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {urls.map((u, i) => (
                <tr key={i} className="hover:bg-secondary/40/80 transition">
                  <td className="p-2.5">
                    <input
                      type="text"
                      value={u.path}
                      onChange={(e) => updateUrl(i, 'path', e.target.value)}
                      className="w-full px-2.5 py-1.5 border border-border rounded-md font-mono text-xs focus:ring-1 focus:ring-indigo-500 focus:outline-hidden"
                    />
                  </td>
                  <td className="p-2.5">
                    <input
                      type="date"
                      value={u.lastmod}
                      onChange={(e) => updateUrl(i, 'lastmod', e.target.value)}
                      className="w-full px-2 py-1.5 border border-border rounded-md text-xs focus:outline-hidden"
                    />
                  </td>
                  <td className="p-2.5">
                    <select
                      value={u.changefreq}
                      onChange={(e) => updateUrl(i, 'changefreq', e.target.value)}
                      className="w-full px-2 py-1.5 border border-border rounded-md text-xs focus:outline-hidden bg-white"
                    >
                      <option value="always">always</option>
                      <option value="hourly">hourly</option>
                      <option value="daily">daily</option>
                      <option value="weekly">weekly</option>
                      <option value="monthly">monthly</option>
                      <option value="yearly">yearly</option>
                      <option value="never">never</option>
                    </select>
                  </td>
                  <td className="p-2.5">
                    <select
                      value={u.priority}
                      onChange={(e) => updateUrl(i, 'priority', e.target.value)}
                      className="w-full px-2 py-1.5 border border-border rounded-md text-xs focus:outline-hidden bg-white font-mono"
                    >
                      <option value="1.0">1.0 (Highest)</option>
                      <option value="0.9">0.9</option>
                      <option value="0.8">0.8 (Default)</option>
                      <option value="0.7">0.7</option>
                      <option value="0.5">0.5</option>
                      <option value="0.3">0.3</option>
                      <option value="0.1">0.1 (Lowest)</option>
                    </select>
                  </td>
                  <td className="p-2.5 text-center">
                    <button
                      onClick={() => removeUrl(i)}
                      className="p-1 text-muted-foreground hover:text-rose-600 rounded transition"
                      title="Delete entry"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* XML Code Output */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <h4 className="font-semibold text-foreground text-sm flex items-center gap-2">
            <Code className="w-4 h-4 text-indigo-600" /> XML Output Preview
          </h4>
          <div className="flex items-center gap-2">
            <button
              onClick={() => copyToClipboard(xmlContent, setCopied)}
              className="px-3 py-1.5 text-xs font-medium rounded-lg bg-indigo-600 text-white hover:bg-indigo-700 flex items-center gap-1 transition"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied XML' : 'Copy XML'}
            </button>
            <button
              onClick={() => downloadFile('sitemap.xml', xmlContent, 'application/xml')}
              className="px-3 py-1.5 text-xs font-medium rounded-lg bg-secondary/60 text-foreground hover:bg-secondary flex items-center gap-1 transition"
            >
              <Download className="w-3.5 h-3.5" /> Download sitemap.xml
            </button>
          </div>
        </div>

        <pre className="bg-slate-900 text-emerald-400 p-4 rounded-xl text-xs font-mono overflow-x-auto max-h-[350px] leading-relaxed border border-slate-800">
          {xmlContent}
        </pre>
      </div>

      {/* Bulk Paste Modal */}
      {showBulkModal && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-xl max-w-lg w-full p-5 space-y-4 shadow-xl">
            <h3 className="text-base font-bold text-foreground">Bulk Import URLs</h3>
            <p className="text-xs text-muted-foreground">
              Paste URLs or paths (one per line). They will be automatically parsed into the sitemap editor.
            </p>
            <textarea
              rows={6}
              value={bulkInput}
              onChange={(e) => setBulkInput(e.target.value)}
              placeholder={`/about\n/services\nhttps://example.com/blog/article-1\n/contact`}
              className="w-full p-3 border border-border rounded-lg text-xs font-mono focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
            />
            <div className="flex justify-end gap-2">
              <button
                onClick={() => setShowBulkModal(false)}
                className="px-3 py-2 text-xs font-medium text-muted-foreground hover:bg-secondary/60 rounded-lg"
              >
                Cancel
              </button>
              <button
                onClick={handleBulkImport}
                className="px-4 py-2 text-xs font-medium bg-indigo-600 text-white hover:bg-indigo-700 rounded-lg"
              >
                Import URLs
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

// ============================================================================
// 3. Open Graph & Social Card Previewer
// ============================================================================
export const OpenGraphPreviewer: React.FC = () => {
  const [title, setTitle] = useState('Ultimate Developer Tools Suite & Free Online Utilities');
  const [description, setDescription] = useState(
    'Access over 50+ free, fast, browser-based online developer tools including JSON formatters, QR code generators, regex testers, and image compressors.'
  );
  const [siteName, setSiteName] = useState('WebTools Studio');
  const [url, setUrl] = useState('https://example.com/tools');
  const [imageUrl, setImageUrl] = useState('https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&h=630&fit=crop');
  const [twitterCard, setTwitterCard] = useState<'summary_large_image' | 'summary'>('summary_large_image');
  const [twitterHandle, setTwitterHandle] = useState('@webtools');
  const [platform, setPlatform] = useState<'facebook' | 'twitter' | 'linkedin' | 'google' | 'discord'>('facebook');
  const [copied, setCopied] = useState(false);

  const titleLength = title.length;
  const descLength = description.length;

  const generatedTags = useMemo(() => {
    return `<!-- Primary Meta Tags -->
<title>${title}</title>
<meta name="title" content="${title}">
<meta name="description" content="${description}">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="${url}">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${description}">
<meta property="og:image" content="${imageUrl}">
<meta property="og:site_name" content="${siteName}">

<!-- Twitter -->
<meta property="twitter:card" content="${twitterCard}">
<meta property="twitter:url" content="${url}">
<meta property="twitter:title" content="${title}">
<meta property="twitter:description" content="${description}">
<meta property="twitter:image" content="${imageUrl}">
<meta property="twitter:site" content="${twitterHandle}">`;
  }, [title, description, siteName, url, imageUrl, twitterCard, twitterHandle]);

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Input Form */}
        <div className="lg:col-span-6 space-y-4 bg-card border border-border rounded-xl p-5 shadow-xs">
          <h4 className="font-semibold text-foreground text-sm flex items-center gap-2">
            <Settings className="w-4 h-4 text-indigo-600" /> Open Graph & Meta Content
          </h4>

          <div>
            <div className="flex justify-between items-center mb-1">
              <label className="text-xs font-semibold text-foreground">Meta Title</label>
              <span className={`text-[10px] font-mono ${titleLength > 60 ? 'text-rose-600 font-bold' : 'text-muted-foreground'}`}>
                {titleLength}/60 chars
              </span>
            </div>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full px-3 py-2 text-xs border border-border rounded-lg focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
            />
          </div>

          <div>
            <div className="flex justify-between items-center mb-1">
              <label className="text-xs font-semibold text-foreground">Meta Description</label>
              <span className={`text-[10px] font-mono ${descLength > 160 ? 'text-rose-600 font-bold' : 'text-muted-foreground'}`}>
                {descLength}/160 chars
              </span>
            </div>
            <textarea
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="w-full p-3 text-xs border border-border rounded-lg focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-semibold text-foreground mb-1">Site Name</label>
              <input
                type="text"
                value={siteName}
                onChange={(e) => setSiteName(e.target.value)}
                className="w-full px-3 py-2 text-xs border border-border rounded-lg focus:outline-hidden"
              />
            </div>
            <div>
              <label className="block text-xs font-semibold text-foreground mb-1">Twitter Handle</label>
              <input
                type="text"
                value={twitterHandle}
                onChange={(e) => setTwitterHandle(e.target.value)}
                className="w-full px-3 py-2 text-xs border border-border rounded-lg focus:outline-hidden"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-foreground mb-1">Page URL</label>
            <input
              type="url"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              className="w-full px-3 py-2 text-xs border border-border rounded-lg font-mono focus:outline-hidden"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-foreground mb-1">OG Share Image URL (1200 x 630 px)</label>
            <input
              type="url"
              value={imageUrl}
              onChange={(e) => setImageUrl(e.target.value)}
              className="w-full px-3 py-2 text-xs border border-border rounded-lg font-mono focus:outline-hidden"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-foreground mb-1">Twitter Card Type</label>
            <div className="flex gap-4 text-xs">
              <label className="flex items-center gap-1.5 cursor-pointer">
                <input
                  type="radio"
                  name="twitterCard"
                  value="summary_large_image"
                  checked={twitterCard === 'summary_large_image'}
                  onChange={() => setTwitterCard('summary_large_image')}
                  className="text-indigo-600 focus:ring-indigo-500"
                />
                Summary with Large Image
              </label>
              <label className="flex items-center gap-1.5 cursor-pointer">
                <input
                  type="radio"
                  name="twitterCard"
                  value="summary"
                  checked={twitterCard === 'summary'}
                  onChange={() => setTwitterCard('summary')}
                  className="text-indigo-600 focus:ring-indigo-500"
                />
                Small Thumbnail
              </label>
            </div>
          </div>
        </div>

        {/* Right: Live Social Card Simulator */}
        <div className="lg:col-span-6 space-y-4">
          {/* Platform Tabs */}
          <div className="flex border-b border-border gap-1 overflow-x-auto">
            {(['facebook', 'twitter', 'linkedin', 'google', 'discord'] as const).map((p) => (
              <button
                key={p}
                onClick={() => setPlatform(p)}
                className={`px-3 py-2 text-xs font-medium capitalize border-b-2 transition ${
                  platform === p
                    ? 'border-indigo-600 text-indigo-600 font-semibold'
                    : 'border-transparent text-muted-foreground hover:text-foreground'
                }`}
              >
                {p}
              </button>
            ))}
          </div>

          {/* Card Container */}
          <div className="bg-secondary/40 p-6 rounded-xl border border-border min-h-[300px] flex items-center justify-center">
            {platform === 'facebook' && (
              <div className="bg-card rounded-lg border border-border overflow-hidden max-w-md w-full shadow-xs">
                <div className="h-48 bg-muted overflow-hidden relative">
                  {imageUrl ? (
                    <img src={imageUrl} alt="OG" className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center text-muted-foreground text-xs">No Image Provided</div>
                  )}
                </div>
                <div className="p-3 bg-secondary/20 border-t border-border space-y-1">
                  <span className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold font-mono">
                    {new URL(url || 'https://example.com').hostname}
                  </span>
                  <h5 className="font-bold text-foreground text-sm line-clamp-1">{title || 'Page Title'}</h5>
                  <p className="text-xs text-muted-foreground line-clamp-2">{description || 'Page description preview...'}</p>
                </div>
              </div>
            )}

            {platform === 'twitter' && (
              <div className="bg-card rounded-2xl border border-border overflow-hidden max-w-md w-full shadow-xs">
                {twitterCard === 'summary_large_image' ? (
                  <div>
                    <div className="h-48 bg-muted overflow-hidden">
                      <img src={imageUrl} alt="Twitter" className="w-full h-full object-cover" />
                    </div>
                    <div className="p-3 space-y-1">
                      <h5 className="font-bold text-foreground text-sm line-clamp-1">{title}</h5>
                      <p className="text-xs text-muted-foreground line-clamp-2">{description}</p>
                      <span className="text-[11px] text-muted-foreground block pt-1 font-mono">
                        🔗 {new URL(url || 'https://example.com').hostname}
                      </span>
                    </div>
                  </div>
                ) : (
                  <div className="p-3 flex gap-3 items-center">
                    <img src={imageUrl} alt="Twitter" className="w-20 h-20 rounded-xl object-cover" />
                    <div className="flex-1 space-y-1">
                      <span className="text-[10px] text-muted-foreground">{new URL(url || 'https://example.com').hostname}</span>
                      <h5 className="font-bold text-foreground text-xs line-clamp-1">{title}</h5>
                      <p className="text-[11px] text-muted-foreground line-clamp-2">{description}</p>
                    </div>
                  </div>
                )}
              </div>
            )}

            {platform === 'google' && (
              <div className="bg-card p-4 rounded-xl border border-border max-w-md w-full space-y-1 shadow-xs">
                <div className="flex items-center gap-2 text-xs">
                  <div className="w-6 h-6 rounded-full bg-secondary flex items-center justify-center font-bold text-foreground text-[10px]">
                    {siteName.charAt(0)}
                  </div>
                  <div>
                    <span className="font-semibold text-foreground text-xs block">{siteName}</span>
                    <span className="text-[11px] text-muted-foreground truncate block font-mono">{url}</span>
                  </div>
                </div>
                <h4 className="text-primary font-medium text-base hover:underline cursor-pointer pt-1 line-clamp-1">
                  {title}
                </h4>
                <p className="text-xs text-muted-foreground line-clamp-2 leading-normal">{description}</p>
              </div>
            )}

            {platform === 'discord' && (
              <div className="bg-card text-foreground p-3 rounded-lg border-l-4 border-primary border border-border max-w-md w-full space-y-2 text-xs shadow-xs">
                <span className="text-[10px] text-muted-foreground font-semibold">{siteName}</span>
                <h5 className="font-bold text-primary text-sm hover:underline">{title}</h5>
                <p className="text-muted-foreground leading-relaxed text-[11px]">{description}</p>
                {imageUrl && (
                  <img src={imageUrl} alt="Discord" className="rounded-md max-h-40 w-full object-cover mt-2" />
                )}
              </div>
            )}

            {platform === 'linkedin' && (
              <div className="bg-card rounded-lg border border-border overflow-hidden max-w-md w-full shadow-xs">
                <img src={imageUrl} alt="LinkedIn" className="w-full h-44 object-cover" />
                <div className="p-3 bg-secondary/20 space-y-1 border-t border-border">
                  <h5 className="font-bold text-foreground text-xs line-clamp-1">{title}</h5>
                  <span className="text-[10px] text-muted-foreground font-mono">{new URL(url || 'https://example.com').hostname}</span>
                </div>
              </div>
            )}
          </div>

          {/* HTML Meta Code */}
          <div className="bg-card border border-border rounded-xl p-4 space-y-2">
            <div className="flex justify-between items-center">
              <span className="text-xs font-bold text-foreground uppercase">Generated Meta Tags</span>
              <button
                onClick={() => copyToClipboard(generatedTags, setCopied)}
                className="px-2.5 py-1 text-xs font-medium bg-indigo-600 text-white hover:bg-indigo-700 rounded-lg flex items-center gap-1 transition"
              >
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied' : 'Copy HTML'}
              </button>
            </div>
            <pre className="bg-slate-900 text-slate-200 p-3 rounded-lg text-[11px] font-mono overflow-x-auto max-h-44 leading-relaxed">
              {generatedTags}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
};

// ============================================================================
// 4. Schema.org Structured Data Generator
// ============================================================================
export const SchemaMarkupGenerator: React.FC = () => {
  const [schemaType, setSchemaType] = useState<'Article' | 'Product' | 'LocalBusiness' | 'FAQPage'>('Article');
  const [copied, setCopied] = useState(false);

  // Form states
  const [article, setArticle] = useState({
    headline: 'How to Optimize Web Application Performance in 2026',
    image: 'https://example.com/cover.jpg',
    author: 'Sarah Jenkins',
    publisher: 'Tech Daily Insights',
    publisherLogo: 'https://example.com/logo.png',
    datePublished: '2026-08-01',
  });

  const [product, setProduct] = useState({
    name: 'Ergonomic Wireless Keyboard Pro',
    image: 'https://example.com/keyboard.jpg',
    description: 'Mechanical keyboard with Bluetooth 5.2 and RGB backlighting.',
    brand: 'TechGear',
    sku: 'TG-KB-2026',
    price: '129.99',
    currency: 'USD',
    availability: 'https://schema.org/InStock',
  });

  const [faqList, setFaqList] = useState([
    { q: 'What payment methods do you accept?', a: 'We accept Visa, MasterCard, PayPal, and Apple Pay.' },
    { q: 'How long does shipping take?', a: 'Standard shipping takes 3-5 business days across North America.' },
  ]);

  const jsonLd = useMemo(() => {
    let obj: any = {};

    if (schemaType === 'Article') {
      obj = {
        '@context': 'https://schema.org',
        '@type': 'Article',
        headline: article.headline,
        image: [article.image],
        datePublished: article.datePublished,
        author: {
          '@type': 'Person',
          name: article.author,
        },
        publisher: {
          '@type': 'Organization',
          name: article.publisher,
          logo: {
            '@type': 'ImageObject',
            url: article.publisherLogo,
          },
        },
      };
    } else if (schemaType === 'Product') {
      obj = {
        '@context': 'https://schema.org',
        '@type': 'Product',
        name: product.name,
        image: [product.image],
        description: product.description,
        sku: product.sku,
        brand: {
          '@type': 'Brand',
          name: product.brand,
        },
        offers: {
          '@type': 'Offer',
          priceCurrency: product.currency,
          price: product.price,
          availability: product.availability,
        },
      };
    } else if (schemaType === 'FAQPage') {
      obj = {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        mainEntity: faqList.map((item) => ({
          '@type': 'Question',
          name: item.q,
          acceptedAnswer: {
            '@type': 'Answer',
            text: item.a,
          },
        })),
      };
    }

    return `<script type="application/ld+json">\n${JSON.stringify(obj, null, 2)}\n</script>`;
  }, [schemaType, article, product, faqList]);

  return (
    <div className="space-y-6">
      {/* Type Selector Tabs */}
      <div className="flex flex-wrap gap-2 border-b border-border pb-3">
        {(['Article', 'Product', 'FAQPage'] as const).map((t) => (
          <button
            key={t}
            onClick={() => setSchemaType(t)}
            className={`px-4 py-2 rounded-lg text-xs font-semibold transition ${
              schemaType === t
                ? 'bg-indigo-600 text-white shadow-xs'
                : 'bg-secondary/60 text-foreground hover:bg-secondary'
            }`}
          >
            {t === 'FAQPage' ? 'FAQ Page' : t} Schema
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Form Controls */}
        <div className="lg:col-span-6 bg-card border border-border rounded-xl p-5 space-y-4 shadow-xs">
          {schemaType === 'Article' && (
            <>
              <div>
                <label className="block text-xs font-semibold text-foreground mb-1">Headline</label>
                <input
                  type="text"
                  value={article.headline}
                  onChange={(e) => setArticle({ ...article, headline: e.target.value })}
                  className="w-full px-3 py-2 text-xs border border-border rounded-lg"
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-foreground mb-1">Author Name</label>
                  <input
                    type="text"
                    value={article.author}
                    onChange={(e) => setArticle({ ...article, author: e.target.value })}
                    className="w-full px-3 py-2 text-xs border border-border rounded-lg"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-foreground mb-1">Publisher Name</label>
                  <input
                    type="text"
                    value={article.publisher}
                    onChange={(e) => setArticle({ ...article, publisher: e.target.value })}
                    className="w-full px-3 py-2 text-xs border border-border rounded-lg"
                  />
                </div>
              </div>
              <div>
                <label className="block text-xs font-semibold text-foreground mb-1">Featured Image URL</label>
                <input
                  type="url"
                  value={article.image}
                  onChange={(e) => setArticle({ ...article, image: e.target.value })}
                  className="w-full px-3 py-2 text-xs border border-border rounded-lg font-mono"
                />
              </div>
            </>
          )}

          {schemaType === 'Product' && (
            <>
              <div>
                <label className="block text-xs font-semibold text-foreground mb-1">Product Name</label>
                <input
                  type="text"
                  value={product.name}
                  onChange={(e) => setProduct({ ...product, name: e.target.value })}
                  className="w-full px-3 py-2 text-xs border border-border rounded-lg"
                />
              </div>
              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-foreground mb-1">Price</label>
                  <input
                    type="text"
                    value={product.price}
                    onChange={(e) => setProduct({ ...product, price: e.target.value })}
                    className="w-full px-3 py-2 text-xs border border-border rounded-lg font-mono"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-foreground mb-1">Currency</label>
                  <input
                    type="text"
                    value={product.currency}
                    onChange={(e) => setProduct({ ...product, currency: e.target.value })}
                    className="w-full px-3 py-2 text-xs border border-border rounded-lg uppercase"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-foreground mb-1">Brand</label>
                  <input
                    type="text"
                    value={product.brand}
                    onChange={(e) => setProduct({ ...product, brand: e.target.value })}
                    className="w-full px-3 py-2 text-xs border border-border rounded-lg"
                  />
                </div>
              </div>
            </>
          )}

          {schemaType === 'FAQPage' && (
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-xs font-bold text-foreground">Questions & Answers</span>
                <button
                  onClick={() => setFaqList([...faqList, { q: 'New Question?', a: 'Answer...' }])}
                  className="px-2.5 py-1 text-xs font-medium bg-indigo-50 text-indigo-600 rounded-lg flex items-center gap-1"
                >
                  <Plus className="w-3.5 h-3.5" /> Add Q&A
                </button>
              </div>
              {faqList.map((item, idx) => (
                <div key={idx} className="p-3 bg-secondary/40 border border-border rounded-lg space-y-2">
                  <input
                    type="text"
                    value={item.q}
                    onChange={(e) => {
                      const updated = [...faqList];
                      updated[idx].q = e.target.value;
                      setFaqList(updated);
                    }}
                    placeholder="Question"
                    className="w-full px-2.5 py-1 text-xs border border-border rounded bg-white font-medium"
                  />
                  <textarea
                    rows={2}
                    value={item.a}
                    onChange={(e) => {
                      const updated = [...faqList];
                      updated[idx].a = e.target.value;
                      setFaqList(updated);
                    }}
                    placeholder="Answer"
                    className="w-full p-2 text-xs border border-border rounded bg-white"
                  />
                </div>
              ))}
            </div>
          )}
        </div>

        {/* JSON-LD Output */}
        <div className="lg:col-span-6 space-y-3">
          <div className="flex justify-between items-center">
            <h4 className="font-semibold text-foreground text-sm flex items-center gap-2">
              <Code className="w-4 h-4 text-indigo-600" /> Output JSON-LD Script
            </h4>
            <button
              onClick={() => copyToClipboard(jsonLd, setCopied)}
              className="px-3 py-1.5 text-xs font-medium bg-indigo-600 text-white rounded-lg flex items-center gap-1"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy Code'}
            </button>
          </div>
          <pre className="bg-slate-900 text-emerald-400 p-4 rounded-xl text-xs font-mono overflow-x-auto min-h-[320px] leading-relaxed border border-slate-800">
            {jsonLd}
          </pre>
        </div>
      </div>
    </div>
  );
};

// ============================================================================
// 5. Keyword Density & N-Gram Analyzer
// ============================================================================
export const KeywordDensityAnalyzer: React.FC = () => {
  const [text, setText] = useState(
    `Search Engine Optimization (SEO) is the process of improving the quality and quantity of website traffic from search engines. SEO targets unpaid traffic rather than direct traffic or paid traffic. High quality content, keyword research, meta tags, and backlink building are fundamental aspects of effective SEO strategy.`
  );
  const [minWordLength, setMinWordLength] = useState(3);
  const [ignoreStopWords, setIgnoreStopWords] = useState(true);

  const stopWords = useMemo(
    () =>
      new Set([
        'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i', 'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me'
      ]),
    []
  );

  const stats = useMemo(() => {
    const cleanText = text.toLowerCase().replace(/[^a-z0-9\s]/g, ' ');
    const rawWords = cleanText.split(/\s+/).filter(Boolean);
    const totalWords = rawWords.length;

    const filteredWords = rawWords.filter((w) => {
      if (w.length < minWordLength) return false;
      if (ignoreStopWords && stopWords.has(w)) return false;
      return true;
    });

    // 1-Gram Density
    const freq: Record<string, number> = {};
    filteredWords.forEach((w) => {
      freq[w] = (freq[w] || 0) + 1;
    });

    const singleKeywords = Object.entries(freq)
      .map(([word, count]) => ({
        word,
        count,
        density: totalWords > 0 ? ((count / totalWords) * 100).toFixed(2) : '0',
      }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 15);

    // 2-Gram Phrases
    const phrases2: Record<string, number> = {};
    for (let i = 0; i < rawWords.length - 1; i++) {
      const p = `${rawWords[i]} ${rawWords[i + 1]}`;
      if (!ignoreStopWords || (!stopWords.has(rawWords[i]) && !stopWords.has(rawWords[i + 1]))) {
        phrases2[p] = (phrases2[p] || 0) + 1;
      }
    }

    const doubleKeywords = Object.entries(phrases2)
      .filter(([_, count]) => count > 1)
      .map(([phrase, count]) => ({
        phrase,
        count,
        density: totalWords > 0 ? ((count / totalWords) * 100).toFixed(2) : '0',
      }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 10);

    return {
      totalWords,
      uniqueWords: new Set(rawWords).size,
      readingTime: Math.ceil(totalWords / 200),
      singleKeywords,
      doubleKeywords,
    };
  }, [text, minWordLength, ignoreStopWords, stopWords]);

  return (
    <div className="space-y-6">
      {/* Top Controls */}
      <div className="bg-secondary/40 border border-border rounded-xl p-4 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-4 text-xs">
          <label className="flex items-center gap-1.5 cursor-pointer font-medium text-foreground">
            <input
              type="checkbox"
              checked={ignoreStopWords}
              onChange={(e) => setIgnoreStopWords(e.target.checked)}
              className="rounded text-indigo-600 focus:ring-indigo-500"
            />
            Filter Stop Words (the, and, in...)
          </label>
        </div>
        <div className="flex items-center gap-2 text-xs">
          <span className="text-muted-foreground font-medium">Min Word Length:</span>
          <input
            type="number"
            min={1}
            max={10}
            value={minWordLength}
            onChange={(e) => setMinWordLength(Number(e.target.value))}
            className="w-16 px-2 py-1 border border-border rounded bg-white text-center font-mono"
          />
        </div>
      </div>

      {/* Input Text Box */}
      <div className="space-y-2">
        <label className="block text-xs font-semibold text-foreground">Article Content / HTML Text</label>
        <textarea
          rows={5}
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Paste your blog post or web copy here..."
          className="w-full p-3 text-xs border border-border rounded-xl focus:ring-2 focus:ring-indigo-500 focus:outline-hidden"
        />
      </div>

      {/* Quick Metrics Bar */}
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
        <div className="bg-card border border-border p-3 rounded-xl text-center">
          <span className="text-muted-foreground text-[10px] uppercase font-bold tracking-wider">Total Words</span>
          <p className="text-lg font-bold text-foreground">{stats.totalWords}</p>
        </div>
        <div className="bg-card border border-border p-3 rounded-xl text-center">
          <span className="text-muted-foreground text-[10px] uppercase font-bold tracking-wider">Unique Words</span>
          <p className="text-lg font-bold text-foreground">{stats.uniqueWords}</p>
        </div>
        <div className="bg-card border border-border p-3 rounded-xl text-center col-span-2 sm:col-span-1">
          <span className="text-muted-foreground text-[10px] uppercase font-bold tracking-wider">Est. Read Time</span>
          <p className="text-lg font-bold text-foreground">{stats.readingTime} min</p>
        </div>
      </div>

      {/* Density Tables */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Single Words Table */}
        <div className="bg-card border border-border rounded-xl overflow-hidden shadow-xs">
          <div className="p-3 bg-secondary/40 border-b border-border font-bold text-xs text-foreground">
            Top Single Keywords (1-Gram)
          </div>
          <table className="w-full text-left text-xs">
            <thead className="bg-secondary/60 text-muted-foreground font-semibold border-b">
              <tr>
                <th className="p-2.5">Keyword</th>
                <th className="p-2.5 text-center">Count</th>
                <th className="p-2.5 text-right">Density %</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {stats.singleKeywords.map((k, idx) => (
                <tr key={idx} className="hover:bg-secondary/40">
                  <td className="p-2.5 font-medium text-foreground">{k.word}</td>
                  <td className="p-2.5 text-center font-mono">{k.count}</td>
                  <td className="p-2.5 text-right font-mono font-semibold text-indigo-600">{k.density}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* 2-Word Phrases Table */}
        <div className="bg-card border border-border rounded-xl overflow-hidden shadow-xs">
          <div className="p-3 bg-secondary/40 border-b border-border font-bold text-xs text-foreground">
            Top 2-Word Phrases (2-Gram)
          </div>
          <table className="w-full text-left text-xs">
            <thead className="bg-secondary/60 text-muted-foreground font-semibold border-b">
              <tr>
                <th className="p-2.5">Phrase</th>
                <th className="p-2.5 text-center">Count</th>
                <th className="p-2.5 text-right">Density %</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {stats.doubleKeywords.length > 0 ? (
                stats.doubleKeywords.map((k, idx) => (
                  <tr key={idx} className="hover:bg-secondary/40">
                    <td className="p-2.5 font-medium text-foreground">{k.phrase}</td>
                    <td className="p-2.5 text-center font-mono">{k.count}</td>
                    <td className="p-2.5 text-right font-mono font-semibold text-indigo-600">{k.density}%</td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={3} className="p-4 text-center text-muted-foreground text-xs">
                    No repeating 2-word phrases found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

// ============================================================================
// 6. Serp Snippet Optimizer & CTR Previewer
// ============================================================================
export const SerpSnippetOptimizer: React.FC = () => {
  const [title, setTitle] = useState('Best Web Development Tools & Utilities in 2026 - Free Online Suite');
  const [description, setDescription] = useState(
    'Discover the top 50+ developer tools online. Free JSON formatter, QR code generator, image compressor, and SEO generators designed for maximum efficiency.'
  );
  const [url, setUrl] = useState('https://webtools.com/seo-suite');
  const [keyword, setKeyword] = useState('developer tools');
  const [viewMode, setViewMode] = useState<'desktop' | 'mobile'>('desktop');

  const titlePixelWidth = Math.round(title.length * 9.5); // Approx pixel formula
  const descPixelWidth = Math.round(description.length * 6.2);

  // Score calculation
  const score = useMemo(() => {
    let s = 100;
    if (title.length < 30 || title.length > 60) s -= 20;
    if (description.length < 120 || description.length > 160) s -= 20;
    if (keyword && !title.toLowerCase().includes(keyword.toLowerCase())) s -= 25;
    if (keyword && !description.toLowerCase().includes(keyword.toLowerCase())) s -= 20;
    if (!/\d+/.test(title)) s -= 10; // Numbers boost CTR
    return Math.max(0, s);
  }, [title, description, keyword]);

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Form Inputs */}
        <div className="lg:col-span-6 space-y-4 bg-card border border-border rounded-xl p-5 shadow-xs">
          <h4 className="font-semibold text-foreground text-sm flex items-center gap-2">
            <Settings className="w-4 h-4 text-indigo-600" /> SERP Snippet Settings
          </h4>

          <div>
            <label className="block text-xs font-semibold text-foreground mb-1">Target Keyword</label>
            <input
              type="text"
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              placeholder="e.g. developer tools"
              className="w-full px-3 py-2 text-xs border border-border rounded-lg focus:outline-hidden"
            />
          </div>

          <div>
            <div className="flex justify-between items-center mb-1">
              <label className="text-xs font-semibold text-foreground">SEO Title Tag</label>
              <span className={`text-[10px] font-mono ${title.length > 60 ? 'text-rose-600 font-bold' : 'text-muted-foreground'}`}>
                {title.length}/60 chars ({titlePixelWidth}px)
              </span>
            </div>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full px-3 py-2 text-xs border border-border rounded-lg"
            />
          </div>

          <div>
            <div className="flex justify-between items-center mb-1">
              <label className="text-xs font-semibold text-foreground">Meta Description</label>
              <span className={`text-[10px] font-mono ${description.length > 160 ? 'text-rose-600 font-bold' : 'text-muted-foreground'}`}>
                {description.length}/160 chars ({descPixelWidth}px)
              </span>
            </div>
            <textarea
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="w-full p-3 text-xs border border-border rounded-lg"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-foreground mb-1">Display URL</label>
            <input
              type="text"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              className="w-full px-3 py-2 text-xs border border-border rounded-lg font-mono"
            />
          </div>
        </div>

        {/* Live SERP Preview & Score */}
        <div className="lg:col-span-6 space-y-4">
          <div className="flex items-center justify-between border-b border-border pb-2">
            <span className="text-xs font-bold text-foreground uppercase">Google SERP Preview</span>
            <div className="flex gap-2">
              <button
                onClick={() => setViewMode('desktop')}
                className={`px-3 py-1 text-xs rounded-lg font-medium ${
                  viewMode === 'desktop' ? 'bg-indigo-600 text-white' : 'bg-secondary/60 text-muted-foreground'
                }`}
              >
                Desktop
              </button>
              <button
                onClick={() => setViewMode('mobile')}
                className={`px-3 py-1 text-xs rounded-lg font-medium ${
                  viewMode === 'mobile' ? 'bg-indigo-600 text-white' : 'bg-secondary/60 text-muted-foreground'
                }`}
              >
                Mobile
              </button>
            </div>
          </div>

          <div className="bg-white p-5 rounded-xl border border-border shadow-xs space-y-1 font-sans">
            <div className="text-[12px] text-[#202124] flex items-center gap-1.5 font-normal truncate">
              <span className="w-4 h-4 bg-slate-200 rounded-full flex items-center justify-center text-[9px] font-bold">G</span>
              <span className="truncate">{url}</span>
            </div>
            <h3 className="text-[#1a0dab] hover:underline text-lg font-normal cursor-pointer line-clamp-1 leading-snug">
              {title || 'Title snippet preview...'}
            </h3>
            <p className="text-[#4d5156] text-xs leading-normal line-clamp-2">
              {description || 'Meta description snippet preview...'}
            </p>
          </div>

          {/* CTR Scorecard */}
          <div className="bg-indigo-50 border border-indigo-100 rounded-xl p-4 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-indigo-950 uppercase">CTR Optimization Score</span>
              <span className="text-base font-black text-indigo-700">{score}/100</span>
            </div>
            <div className="w-full bg-indigo-200 rounded-full h-2 overflow-hidden">
              <div className="bg-indigo-600 h-full transition-all duration-300" style={{ width: `${score}%` }} />
            </div>
            <ul className="text-[11px] text-indigo-900 space-y-1 font-medium">
              <li className="flex items-center gap-1">
                {title.length >= 30 && title.length <= 60 ? '✅' : '⚠️'} Title length within 30-60 characters
              </li>
              <li className="flex items-center gap-1">
                {keyword && title.toLowerCase().includes(keyword.toLowerCase()) ? '✅' : '⚠️'} Keyword included in Title
              </li>
              <li className="flex items-center gap-1">
                {/\d+/.test(title) ? '✅' : '💡'} Includes numbers/year for higher click-through rate
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

// ============================================================================
// 7. Hreflang Tag & Redirect Code Generator
// ============================================================================
export const HrefLangRedirectGenerator: React.FC = () => {
  const [mode, setMode] = useState<'hreflang' | 'redirect'>('hreflang');
  const [copied, setCopied] = useState(false);

  // Hreflang State
  const [baseUrl, setBaseUrl] = useState('https://example.com/page');
  const [languages, setLanguages] = useState([
    { lang: 'en-us', path: 'https://example.com/us/page' },
    { lang: 'es-es', path: 'https://example.com/es/page' },
    { lang: 'de-de', path: 'https://example.com/de/page' },
    { lang: 'x-default', path: 'https://example.com/page' },
  ]);

  // Redirect State
  const [redirects, setRedirects] = useState([
    { oldUrl: '/old-blog-post', newUrl: '/blog/new-post', code: '301' },
    { oldUrl: '/pricing-2025', newUrl: '/pricing', code: '301' },
  ]);

  const hreflangTags = useMemo(() => {
    return languages
      .map((l) => `<link rel="alternate" hreflang="${l.lang}" href="${l.path}" />`)
      .join('\n');
  }, [languages]);

  const htaccessCode = useMemo(() => {
    let code = `# 301 Redirects\nRewriteEngine On\n`;
    redirects.forEach((r) => {
      code += `Redirect ${r.code} ${r.oldUrl} ${r.newUrl}\n`;
    });
    return code;
  }, [redirects]);

  return (
    <div className="space-y-6">
      {/* Sub-mode Switcher */}
      <div className="flex gap-2 border-b border-border pb-3">
        <button
          onClick={() => setMode('hreflang')}
          className={`px-4 py-2 text-xs font-bold rounded-lg transition ${
            mode === 'hreflang' ? 'bg-indigo-600 text-white' : 'bg-secondary/60 text-foreground'
          }`}
        >
          Hreflang Tags Builder
        </button>
        <button
          onClick={() => setMode('redirect')}
          className={`px-4 py-2 text-xs font-bold rounded-lg transition ${
            mode === 'redirect' ? 'bg-indigo-600 text-white' : 'bg-secondary/60 text-foreground'
          }`}
        >
          301 Redirect Rules Generator
        </button>
      </div>

      {mode === 'hreflang' ? (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          <div className="lg:col-span-6 space-y-4 bg-card border border-border rounded-xl p-5 shadow-xs">
            <h4 className="font-semibold text-foreground text-sm">Target Language Versions</h4>
            {languages.map((l, idx) => (
              <div key={idx} className="flex gap-2 items-center">
                <input
                  type="text"
                  value={l.lang}
                  onChange={(e) => {
                    const updated = [...languages];
                    updated[idx].lang = e.target.value;
                    setLanguages(updated);
                  }}
                  className="w-28 px-2.5 py-1.5 text-xs border border-border rounded font-mono"
                />
                <input
                  type="url"
                  value={l.path}
                  onChange={(e) => {
                    const updated = [...languages];
                    updated[idx].path = e.target.value;
                    setLanguages(updated);
                  }}
                  className="flex-1 px-2.5 py-1.5 text-xs border border-border rounded font-mono"
                />
              </div>
            ))}
          </div>

          <div className="lg:col-span-6 space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-xs font-bold text-foreground">HTML Hreflang Code</span>
              <button
                onClick={() => copyToClipboard(hreflangTags, setCopied)}
                className="px-3 py-1.5 text-xs bg-indigo-600 text-white rounded-lg"
              >
                {copied ? 'Copied' : 'Copy HTML'}
              </button>
            </div>
            <pre className="bg-slate-900 text-emerald-400 p-4 rounded-xl text-xs font-mono overflow-x-auto min-h-[220px]">
              {hreflangTags}
            </pre>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          <div className="lg:col-span-6 space-y-4 bg-card border border-border rounded-xl p-5 shadow-xs">
            <h4 className="font-semibold text-foreground text-sm">Redirect Paths</h4>
            {redirects.map((r, idx) => (
              <div key={idx} className="flex gap-2 items-center">
                <input
                  type="text"
                  value={r.oldUrl}
                  onChange={(e) => {
                    const updated = [...redirects];
                    updated[idx].oldUrl = e.target.value;
                    setRedirects(updated);
                  }}
                  placeholder="/old-path"
                  className="flex-1 px-2.5 py-1.5 text-xs border border-border rounded font-mono"
                />
                <span className="text-xs text-muted-foreground">→</span>
                <input
                  type="text"
                  value={r.newUrl}
                  onChange={(e) => {
                    const updated = [...redirects];
                    updated[idx].newUrl = e.target.value;
                    setRedirects(updated);
                  }}
                  placeholder="/new-path"
                  className="flex-1 px-2.5 py-1.5 text-xs border border-border rounded font-mono"
                />
              </div>
            ))}
          </div>

          <div className="lg:col-span-6 space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-xs font-bold text-foreground">Apache .htaccess Output</span>
              <button
                onClick={() => copyToClipboard(htaccessCode, setCopied)}
                className="px-3 py-1.5 text-xs bg-indigo-600 text-white rounded-lg"
              >
                {copied ? 'Copied' : 'Copy Rules'}
              </button>
            </div>
            <pre className="bg-slate-900 text-slate-100 p-4 rounded-xl text-xs font-mono overflow-x-auto min-h-[220px]">
              {htaccessCode}
            </pre>
          </div>
        </div>
      )}
    </div>
  );
};

// ============================================================================
// 8. Heading Structure & Content Hierarchy Analyzer
// ============================================================================
export const HeadingStructureAnalyzer: React.FC = () => {
  const [htmlContent, setHtmlContent] = useState(`<h1>Complete Guide to Web Development</h1>
<h2>Introduction to Frontend Technologies</h2>
<h3>HTML5 and Semantic Markup</h3>
<h3>CSS3 and Responsive Layouts</h3>
<h2>Backend Infrastructure</h2>
<h3>Node.js and Express</h3>
<h4>Database Integration</h4>`);

  const headings = useMemo(() => {
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlContent, 'text/html');
    const elements = doc.querySelectorAll('h1, h2, h3, h4, h5, h6');

    return Array.from(elements).map((el) => ({
      tag: el.tagName.toLowerCase(),
      text: el.textContent || '',
      level: parseInt(el.tagName.replace('H', ''), 10),
    }));
  }, [htmlContent]);

  const h1Count = headings.filter((h) => h.tag === 'h1').length;

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-6 space-y-3">
          <label className="block text-xs font-semibold text-foreground">Paste HTML or Article Structure</label>
          <textarea
            rows={10}
            value={htmlContent}
            onChange={(e) => setHtmlContent(e.target.value)}
            className="w-full p-3 text-xs border border-border rounded-xl font-mono"
          />
        </div>

        <div className="lg:col-span-6 space-y-4">
          <div className="bg-card border border-border rounded-xl p-4 shadow-xs space-y-3">
            <h4 className="font-semibold text-foreground text-sm flex items-center gap-2">
              <Hierarchy className="w-4 h-4 text-indigo-600" /> Heading Tree Outline
            </h4>
            {h1Count !== 1 && (
              <div className="p-2.5 bg-amber-50 border border-amber-200 rounded-lg text-xs text-amber-800 flex items-center gap-1.5">
                <AlertTriangle className="w-4 h-4 text-amber-600" />
                Warning: Best SEO practices recommend having exactly ONE H1 tag on a page (Found: {h1Count}).
              </div>
            )}
            <div className="space-y-1.5 font-mono text-xs max-h-[280px] overflow-y-auto">
              {headings.map((h, i) => (
                <div
                  key={i}
                  style={{ paddingLeft: `${(h.level - 1) * 16}px` }}
                  className="flex items-center gap-2 p-1.5 rounded hover:bg-secondary/40"
                >
                  <span className="px-1.5 py-0.5 text-[10px] bg-slate-200 text-foreground font-bold rounded">
                    {h.tag.toUpperCase()}
                  </span>
                  <span className="text-foreground font-sans truncate">{h.text}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// ============================================================================
// 9. SEO Slug Health Checker & Batch Generator
// ============================================================================
export const SeoSlugHealthChecker: React.FC = () => {
  const [inputTitle, setInputTitle] = useState('Top 10 Web Development Trends for 2026!');
  const [copied, setCopied] = useState(false);

  const cleanSlug = useMemo(() => {
    return inputTitle
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, '')
      .replace(/[\s_-]+/g, '-')
      .replace(/^-+|-+$/g, '');
  }, [inputTitle]);

  return (
    <div className="space-y-6">
      <div className="bg-card border border-border rounded-xl p-5 space-y-4 shadow-xs">
        <h4 className="font-semibold text-foreground text-sm">Title to Clean SEO Slug Converter</h4>
        <div>
          <label className="block text-xs font-semibold text-foreground mb-1">Enter Article / Page Title</label>
          <input
            type="text"
            value={inputTitle}
            onChange={(e) => setInputTitle(e.target.value)}
            className="w-full px-3 py-2 text-xs border border-border rounded-lg"
          />
        </div>

        <div>
          <label className="block text-xs font-semibold text-foreground mb-1">Optimized Clean Slug</label>
          <div className="flex gap-2">
            <input
              type="text"
              readOnly
              value={cleanSlug}
              className="flex-1 px-3 py-2 text-xs border border-indigo-200 bg-indigo-50/50 rounded-lg font-mono text-indigo-900 font-bold"
            />
            <button
              onClick={() => copyToClipboard(cleanSlug, setCopied)}
              className="px-4 py-2 text-xs font-medium bg-indigo-600 text-white rounded-lg flex items-center gap-1"
            >
              {copied ? 'Copied' : 'Copy Slug'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

// ============================================================================
// 10. SEO Content Readability & Text Statistics Audit
// ============================================================================
export const SeoContentReadabilityAudit: React.FC = () => {
  const [content, setContent] = useState(
    `Search Engine Optimization involves optimizing your website content to improve visibility in organic search engine results. Search engines evaluate readability, keyword context, user engagement, and bounce rates when determining page rankings.`
  );

  const readabilityStats = useMemo(() => {
    const sentences = content.split(/[.!?]+/).filter(Boolean);
    const words = content.split(/\s+/).filter(Boolean);

    const totalWords = words.length;
    const totalSentences = sentences.length || 1;

    // Simple syllable counter heuristic
    let totalSyllables = 0;
    words.forEach((w) => {
      const clean = w.toLowerCase().replace(/[^a-z]/g, '');
      totalSyllables += Math.max(1, clean.replace(/[^aeiouy]+/g, '').length);
    });

    // Flesch Reading Ease Formula
    const fleschEase =
      totalWords > 0
        ? Math.round(206.835 - 1.015 * (totalWords / totalSentences) - 84.6 * (totalSyllables / totalWords))
        : 100;

    let easeLabel = 'Easy to read';
    if (fleschEase < 50) easeLabel = 'Difficult / Academic';
    else if (fleschEase < 70) easeLabel = 'Standard / Plain English';

    return {
      totalWords,
      totalSentences,
      avgWordsPerSentence: (totalWords / totalSentences).toFixed(1),
      fleschEase,
      easeLabel,
    };
  }, [content]);

  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <label className="block text-xs font-semibold text-foreground">Paste Web Article Copy</label>
        <textarea
          rows={6}
          value={content}
          onChange={(e) => setContent(e.target.value)}
          className="w-full p-3 text-xs border border-border rounded-xl"
        />
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="bg-card border border-border p-4 rounded-xl text-center shadow-xs">
          <span className="text-[10px] font-bold text-muted-foreground uppercase">Flesch Reading Ease</span>
          <p className="text-2xl font-black text-indigo-600">{readabilityStats.fleschEase}</p>
          <span className="text-xs text-muted-foreground font-medium">{readabilityStats.easeLabel}</span>
        </div>
        <div className="bg-card border border-border p-4 rounded-xl text-center shadow-xs">
          <span className="text-[10px] font-bold text-muted-foreground uppercase">Total Words</span>
          <p className="text-2xl font-black text-foreground">{readabilityStats.totalWords}</p>
        </div>
        <div className="bg-card border border-border p-4 rounded-xl text-center shadow-xs">
          <span className="text-[10px] font-bold text-muted-foreground uppercase">Avg Words / Sentence</span>
          <p className="text-2xl font-black text-foreground">{readabilityStats.avgWordsPerSentence}</p>
        </div>
      </div>
    </div>
  );
};
